#pragma once
#ifndef __GAME_ENUM_H__
#define __GAME_ENUM_H__

enum SKILL_ID { RAISE_SKELETON,BONDE_SPEAR, SKILL_END};
enum PLAYER_STATE { PLAYER_STAND, PLAYER_MOVE, PLAYER_ATTACK, PLAYER_DEAD, PLAYER_END };

#endif // !__GAME_ENUM_H__

