#pragma once
#ifndef __GAME_ENUM_H__
#define __GAME_ENUM_H__

enum SKILL_ID { RAISE_SKELETON,BONE_SPEAR, SKILL_END};
enum PLAYER_STATE { PLAYER_STAND, PLAYER_MOVE, PLAYER_ATTACK, PLAYER_DEAD, PLAYER_END };
enum DIR { BACK, BACK_RIGHT, RIGHT, FRONT_RIGHT, FRONT, FRONT_LEFT, LEFT, BACK_LEFT,DIR_END };

#endif // !__GAME_ENUM_H__

